version: "3"
services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile.influxdb
    ports:
      - "8086:8086"
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_HTTP_PORT=5000
    ports:
      - "5000:5000"
  k6:
    build: .
    ports:
      - "6565:6565"
    volumes:
      - "./test:/test"
    environment:
      - --out influxdb=http://influxdb:8086/k6
    command: "version"
